const ReviewActionTypes = {
  FETCH_REVIEWS_START: 'FETCH_REVIEWS_START',
  FETCH_REVIEWS_SUCCESS: 'FETCH_REVIEWS_SUCCESS',
  FETCH_REVIEWS_FAILURE: 'FETCH_REVIEWS_FAILURE',
  CREATE_REVIEW_START: 'CREATE_REVIEW_START',
  CREATE_REVIEW_SUCCESS: 'CREATE_REVIEW_SUCCESS',
  CREATE_REVIEW_FAILURE: 'CREATE_REVIEW_FAILURE',
  UPDATE_REVIEW_START: 'UPDATE_REVIEW_START',
  UPDATE_REVIEW_SUCCESS: 'UPDATE_REVIEW_SUCCESS',
  UPDATE_REVIEW_FAILURE: 'UPDATE_REVIEW_FAILURE',
  DELETE_REVIEW_START: 'DELETE_REVIEW_START',
  DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
  DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE'
};

export default ReviewActionTypes;
